version: "3"
services:
  keypair-generator.local:
    build:
      context: ../
      dockerfile: ./local/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
    tty: true
